name: Run E2E tests for tgmigrate

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Test
        run: go test -v ./test/e2e
